<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1453" started-at="2018-02-24T13:23:53Z" finished-at="2018-02-24T13:23:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1453" started-at="2018-02-24T13:23:53Z" finished-at="2018-02-24T13:23:54Z">
      <class name="ShortCircuitBreakerPattern">
        <test-method status="FAIL" signature="givenCircuitBreakerSetup_whenRemoteSvcCmdExecuted_thenReturnSuccess()[pri:0, instance:ShortCircuitBreakerPattern@5056dfcb]" name="givenCircuitBreakerSetup_whenRemoteSvcCmdExecuted_thenReturnSuccess" duration-ms="1436" started-at="2018-02-24T18:53:53Z" finished-at="2018-02-24T18:53:54Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at ShortCircuitBreakerPattern.givenCircuitBreakerSetup_whenRemoteSvcCmdExecuted_thenReturnSuccess(ShortCircuitBreakerPattern.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- givenCircuitBreakerSetup_whenRemoteSvcCmdExecuted_thenReturnSuccess -->
      </class> <!-- ShortCircuitBreakerPattern -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
